import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const robotoSlab = Roboto_Slab({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSlab.className} antialiased`}
      >
        <div className=" w-full h-full max-w-[1400px] mx-auto px-[40px]">
          <div className="sticky top-0 z-50 bg-white shadow-sm mx-auto ">
            <Navbar />
          </div>
          <main>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
